name: ToxicSkies
version: 2.5.3
authors: [zarlo5899, DeltaHat]
softdepend: [WorldGuard]
main: com.ryanmichela.toxicskies.TsPlugin
Permissions:
  toxicskies.bypas.*:
    description: bypass ToxicSkies
    default: false
